# Generated by Django 4.0.4 on 2022-05-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll_no', models.CharField(max_length=9, null=True)),
                ('book_name', models.CharField(max_length=30, null=True)),
                ('book_id', models.IntegerField()),
                ('status', models.CharField(choices=[('ISD', 'ISSUED'), ('RTD', 'RETURNED')], default='ISD', max_length=10)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
