# Generated by Django 4.0.4 on 2022-04-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='book',
        ),
        migrations.RemoveField(
            model_name='register',
            name='student',
        ),
        migrations.AddField(
            model_name='register',
            name='book_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='student_roll_no',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
