# Generated by Django 4.0.4 on 2022-04-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('acquired', models.DateTimeField(auto_now_add=True)),
                ('issued', models.DateTimeField(auto_now=True)),
                ('last_returned', models.DateTimeField(auto_now=True)),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
