# Generated by Django 4.0.4 on 2022-05-04 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('last_issued', models.DateTimeField(null=True)),
                ('last_returned', models.DateTimeField(null=True)),
                ('pages', models.IntegerField()),
                ('copies', models.IntegerField(default=1)),
                ('author', models.CharField(default='abc', max_length=25)),
                ('subject', models.CharField(choices=[('MA', 'MATHEMATICS'), ('PH', 'PHYSICS'), ('CH', 'CHEMISTRY'), ('BB', 'BIOLOGY'), ('CS', 'COMPUTER SCIENCE'), ('EE', 'ELECTRICAL'), ('ME', 'MECHANICAL')], default='CS', max_length=20)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.student')),
            ],
        ),
    ]
