# Generated by Django 4.0.4 on 2022-04-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='abc', max_length=25),
        ),
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.CharField(choices=[('MA', 'MATHEMATICS'), ('PH', 'PHYSICS'), ('CH', 'CHEMISTRY'), ('BB', 'BIOLOGY'), ('CS', 'COMPUTER SCIENCE'), ('EE', 'ELECTRICAL'), ('ME', 'MECHANICAL')], default='CS', max_length=20),
        ),
    ]
