# Generated by Django 4.0.4 on 2022-05-04 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='copies',
        ),
    ]
