# Generated by Django 4.0.4 on 2022-05-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='acquired',
            field=models.DateField(null=True),
        ),
    ]
