# Generated by Django 4.0.4 on 2022-04-27 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('book', '0003_book_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.student'),
        ),
    ]
