# Generated by Django 4.0.4 on 2022-04-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='issued',
        ),
        migrations.AddField(
            model_name='book',
            name='last_issued',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_returned',
            field=models.DateTimeField(null=True),
        ),
    ]
