# Generated by Django 4.0.4 on 2022-04-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_book_issued_book_last_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='acquired',
            field=models.DateTimeField(null=True),
        ),
    ]
