# Generated by Django 4.0.4 on 2022-04-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_acquired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='acquired',
        ),
    ]
