# Generated by Django 4.0.4 on 2022-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('book', '0007_remove_book_acquired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='student',
        ),
        migrations.AddField(
            model_name='book',
            name='student',
            field=models.ManyToManyField(null=True, to='student.student'),
        ),
    ]
