# Generated by Django 4.0.4 on 2022-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('book', '0008_remove_book_student_book_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='student',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
