# Generated by Django 4.0.4 on 2022-05-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issued_copies',
            field=models.IntegerField(default=0),
        ),
    ]
