# Generated by Django 4.0.4 on 2022-04-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('roll_no', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
